language: objective-c
osx_image: xcode7.2

before_script:
  - brew install couchdb
  - couchdb &

script:
  - ./setup.rb
  - set -o pipefail && xcodebuild -project SwiftCloudant.xcodeproj -scheme SwiftCloudant -destination 'platform=iOS Simulator,OS=latest,name=iPhone 6S' test |  xcpretty
