language: objective-c
osx_image: xcode7.2

before_script:
  - brew install couchdb
  - couchdb &

script:
  - ./setup.rb
  - xcodebuild -workspace ObjectiveCloudant.xcworkspace/ -scheme SwiftCloudant -destination 'platform=iOS Simulator,OS=latest,name=iPhone 6S' build test |  xcpretty; exit ${PIPESTATUS[0]}
  - pod lib lint
