language: objective-c
osx_image: xcode7.2

before_script:
  - brew install couchdb
  - couchdb &
  - pod install

script:
  - ./setup.rb
  - set -o pipefail && xcodebuild -workspace SwiftCloudant.xcworkspace -scheme SwiftCloudant -destination 'platform=iOS Simulator,OS=latest,name=iPhone 6S' test |  xcpretty
