language: objective-c
xcode_project: ObjectiveCloudant.xcodeproj
xcode_scheme: ObjectiveCloudant

services:
  - couchdb

script:
  - xcodebuild -scheme ObjectiveCloudant build test -sdk iphonesimulator
